variables:
  GIT_STRATEGY: none

stages:
  - build

push-to-transifex:
  stage: build
  only:
    - schedules
  image:
    name: registry.snap.lizlan:5000/infra/transifex-lwc:latest
  script:
    - echo "token = ${TRANSIFEX_TOKEN}" >> /root/.transifexrc
    - echo "password = ${TRANSIFEX_TOKEN}" >> /root/.transifexrc
    # from_lwc_to_transifex LWC_BRANCH LOCALE_BRANCH
    - from_lwc_to_transifex master master
    - from_lwc_to_transifex release_3_5 lizmap_3_5
    - from_lwc_to_transifex release_3_4 lizmap_3_4
  tags:
    - factory-plain
