variables:
  GIT_STRATEGY: none

stages:
  - build

push-to-transifex:
  stage: build
  only:
    - schedules
  image:
    name: $REGISTRY_URI/infra/transifex-lwc:latest
  parallel:
    matrix:

      - LWC_BRANCH: master
        LOCALE_BRANCH: master

      - LWC_BRANCH: release_3_7
        LOCALE_BRANCH: lizmap_3_7

      - LWC_BRANCH: release_3_6
        LOCALE_BRANCH: lizmap_3_6

  script:
    - echo "token = ${TRANSIFEX_TOKEN}" >> /root/.transifexrc
    - echo "password = ${TRANSIFEX_TOKEN}" >> /root/.transifexrc
    - from_lwc_to_transifex ${LWC_BRANCH} ${LOCALE_BRANCH}
  tags:
    - factory-plain

pull-from-transifex-master:
  stage: build
  when: manual
  only:
    - schedules
  image:
    name: $REGISTRY_URI/infra/transifex-lwc:latest
  script:
    - echo "token = ${TRANSIFEX_TOKEN}" >> /root/.transifexrc
    - echo "password = ${TRANSIFEX_TOKEN}" >> /root/.transifexrc
    - from_transifex_to_lwc master master
  tags:
    - factory-plain

pull-from-transifex-3-7:
  stage: build
  when: manual
  only:
    - schedules
  image:
    name: $REGISTRY_URI/infra/transifex-lwc:latest
  script:
    - echo "token = ${TRANSIFEX_TOKEN}" >> /root/.transifexrc
    - echo "password = ${TRANSIFEX_TOKEN}" >> /root/.transifexrc
    - from_transifex_to_lwc release_3_7 lizmap_3_7
  tags:
    - factory-plain

pull-from-transifex-3-6:
  stage: build
  when: manual
  only:
    - schedules
  image:
    name: $REGISTRY_URI/infra/transifex-lwc:latest
  script:
    - echo "token = ${TRANSIFEX_TOKEN}" >> /root/.transifexrc
    - echo "password = ${TRANSIFEX_TOKEN}" >> /root/.transifexrc
    - from_transifex_to_lwc release_3_6 lizmap_3_6
  tags:
    - factory-plain
