variables:
  GIT_STRATEGY: none

stages:
  - build

push-to-transifex:
  stage: build
  only:
    - schedules
  image:
    name: $REGISTRY_URI/infra/transifex-lwc:latest
  parallel:
    matrix:

      - LWC_BRANCH: master
        LOCALE_BRANCH: master

      - LWC_BRANCH: release_3_7
        LOCALE_BRANCH: lizmap_3_7

      - LWC_BRANCH: release_3_8
        LOCALE_BRANCH: lizmap_3_8

  script:
    - export TX_TOKEN=${TRANSIFEX_TOKEN}
    - from_lwc_to_transifex ${LWC_BRANCH} ${LOCALE_BRANCH}
  tags:
    - factory-dind

pull-from-transifex-master:
  stage: build
  when: manual
  only:
    - schedules
  image:
    name: $REGISTRY_URI/infra/transifex-lwc:latest
  script:
    - export TX_TOKEN=${TRANSIFEX_TOKEN}
    - from_transifex_to_lwc master master
  tags:
    - factory-dind

pull-from-transifex-3-7:
  stage: build
  when: manual
  only:
    - schedules
  image:
    name: $REGISTRY_URI/infra/transifex-lwc:latest
  script:
    - export TX_TOKEN=${TRANSIFEX_TOKEN}
    - from_transifex_to_lwc release_3_7 lizmap_3_7
  tags:
    - factory-dind

pull-from-transifex-3-8:
  stage: build
  when: manual
  only:
    - schedules
  image:
    name: $REGISTRY_URI/infra/transifex-lwc:latest
  script:
    - export TX_TOKEN=${TRANSIFEX_TOKEN}
    - from_transifex_to_lwc release_3_8 lizmap_3_8
  tags:
    - factory-dind
