variables:
  GIT_STRATEGY: none

stages:
  - build

push-to-transifex:
  stage: build
  only:
    - schedules
  image:
    name: registry.snap.lizlan:5000/infra/transifex-lwc:latest
  parallel:
    matrix:

      - LWC_BRANCH: master
        LOCALE_BRANCH: master

      - LWC_BRANCH: release_3_6
        LOCALE_BRANCH: lizmap_3_6

      - LWC_BRANCH: release_3_5
        LOCALE_BRANCH: lizmap_3_5

      - LWC_BRANCH: release_3_4
        LOCALE_BRANCH: lizmap_3_4

  script:
    - echo "token = ${TRANSIFEX_TOKEN}" >> /root/.transifexrc
    - echo "password = ${TRANSIFEX_TOKEN}" >> /root/.transifexrc
    - from_lwc_to_transifex ${LWC_BRANCH} ${LOCALE_BRANCH}
  tags:
    - factory-plain

pull-from-transifex-master:
  stage: build
  when: manual
  only:
    - schedules
  image:
    name: registry.snap.lizlan:5000/infra/transifex-lwc:latest
  script:
    - echo "token = ${TRANSIFEX_TOKEN}" >> /root/.transifexrc
    - echo "password = ${TRANSIFEX_TOKEN}" >> /root/.transifexrc
    - from_transifex_to_lwc master master
  tags:
    - factory-plain

pull-from-transifex-3-6:
  stage: build
  when: manual
  only:
    - schedules
  image:
    name: registry.snap.lizlan:5000/infra/transifex-lwc:latest
  script:
    - echo "token = ${TRANSIFEX_TOKEN}" >> /root/.transifexrc
    - echo "password = ${TRANSIFEX_TOKEN}" >> /root/.transifexrc
    - from_transifex_to_lwc release_3_6 lizmap_3_6
  tags:
    - factory-plain


pull-from-transifex-3-5:
  stage: build
  when: manual
  only:
    - schedules
  image:
    name: registry.snap.lizlan:5000/infra/transifex-lwc:latest
  script:
    - echo "token = ${TRANSIFEX_TOKEN}" >> /root/.transifexrc
    - echo "password = ${TRANSIFEX_TOKEN}" >> /root/.transifexrc
    - from_transifex_to_lwc release_3_5 lizmap_3_5
  tags:
    - factory-plain

pull-from-transifex-3-4:
  stage: build
  when: manual
  only:
    - schedules
  image:
    name: registry.snap.lizlan:5000/infra/transifex-lwc:latest
  script:
    - echo "token = ${TRANSIFEX_TOKEN}" >> /root/.transifexrc
    - echo "password = ${TRANSIFEX_TOKEN}" >> /root/.transifexrc
    - from_transifex_to_lwc release_3_4 lizmap_3_4
  tags:
    - factory-plain
